apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: codeshare
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CodeShare123!"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: codeshare
type: Opaque
stringData:
  ConnectionStrings__CodeShareDbConnection: "Host=postgres-service;Database=CodeShareDb;Username=sa;Password=CodeShare123!"
  Jwt__Key: "MLNMu5ppY+ep4ftzVQx0O1r9/iaabOb4qwMQAaXIJys="
  Jwt__Issuer: "ultron682"
  Jwt__Audience: "ultron682"
